 # .github/workflows/cypress.yml
name: Run Cypress Tests

on:
  push:
    branches:
      - main # or the branch you want to trigger the workflow
  pull_request:
    branches:
      - main # or the branch you want to trigger the workflow

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Use the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: 'https://qa.kenyahmis.org/openmrs/spa/login' # Set your base URL if needed

      - name: Upload Cypress results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results # Adjust path to where your test results are stored

